# Site settings
title: Huang Li
email: lihuang55555@gmail.com
description: "Huang Li's Personal Website"
baseurl: "/PersonalWebsite"
url: "http://lihuang.me"

# Build settings
markdown: kramdown
permalink: pretty
