# Site settings
title: Huang Li
email: lihuang55555@gmail.com
description: "Life is meaningful if you can earn respect from people you respect; not envy from people you envy."
baseurl: "/PersonalWebsite"
#url: "http://lihuang.me"
username: "lheric"

# Build settings
markdown: kramdown
permalink: pretty

#image tag
image:
  source: 
  output: generated
  presets:
    users:
      attr:
        class: user-portrait
        itemprop: image
      width: 350
    half:
      width: 400
      height: 400