# Site settings
title: Huang Li
email: lihuang55555@gmail.com
description: "Life is meaningful if you can earn respect from people you respect; not envy from people you envy."
baseurl: "/PersonalWebsite"
#url: "http://lihuang.me"
username: "lheric"

# Build settings
markdown: kramdown
permalink: pretty


flickr_set:
  gallery_tag:   'p'
  gallery_class: 'gallery'
  a_href:        nil
  a_target:      '_blank'
  image_rel:     ''
  image_size:    's'
  api_key:       'd0ba4b2fca4cc10796539f8a8158d46f'