# Site settings
title: Huang Li
email: echo bGlodWFuZzU1NTU1QGdtYWlsLmNvbQo=|base64 -D
description: "Huang Li's Personal Website"
baseurl: "/PersonalWebsite"
url: "http://lihuang.me"

# Build settings
markdown: kramdown
permalink: pretty
